blank_issues_enabled: false
contact_links:
  - name: Features and ideas
    url: https://github.com/flowcourier/Flowcourier.Umbraco.Support/discussions/new?category=ideas
    about: Suggest an idea for this project


